[package]
name = "vmil"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
error = { path = "../library/error" }
lexer = { path = "../library/lexer" }
